export const CATEGORIES = [
  {
    id: 'red',
    title: 'Tinkering - elettronica educativa',
    shortTitle: 'Tinkering',
    icon: 'Wrench',
    colorHex: '#ff3b30',
    badgeClass: 'bg-red-100 text-red-700 border-red-300',
    cardBorderClass: 'border-red-500 hover:border-red-600',
    activeBgClass: 'bg-red-500 text-white shadow-red-200',
    inactiveBgClass: 'bg-white text-slate-700 hover:bg-red-50',
    topBarClass: 'bg-red-500',
    buttonClass: 'bg-red-500 hover:bg-red-600 text-white shadow-red-300',
  },
  {
    id: 'purple',
    title: 'Coding',
    shortTitle: 'Coding',
    icon: 'Code2',
    colorHex: '#8c52ff',
    badgeClass: 'bg-purple-100 text-purple-700 border-purple-300',
    cardBorderClass: 'border-purple-500 hover:border-purple-600',
    activeBgClass: 'bg-purple-600 text-white shadow-purple-200',
    inactiveBgClass: 'bg-white text-slate-700 hover:bg-purple-50',
    topBarClass: 'bg-purple-600',
    buttonClass: 'bg-purple-600 hover:bg-purple-700 text-white shadow-purple-300',
  },
  {
    id: 'blue',
    title: 'Robotica',
    shortTitle: 'Robotica',
    icon: 'Bot',
    colorHex: '#38b6ff',
    badgeClass: 'bg-sky-100 text-sky-700 border-sky-300',
    cardBorderClass: 'border-sky-500 hover:border-sky-600',
    activeBgClass: 'bg-sky-500 text-white shadow-sky-200',
    inactiveBgClass: 'bg-white text-slate-700 hover:bg-sky-50',
    topBarClass: 'bg-sky-500',
    buttonClass: 'bg-sky-500 hover:bg-sky-600 text-white shadow-sky-300',
  },
  {
    id: 'green',
    title: 'Immersività',
    shortTitle: 'Immersività',
    icon: 'Glasses',
    colorHex: '#7ed957',
    badgeClass: 'bg-emerald-100 text-emerald-700 border-emerald-300',
    cardBorderClass: 'border-emerald-500 hover:border-emerald-600',
    activeBgClass: 'bg-emerald-500 text-white shadow-emerald-200',
    inactiveBgClass: 'bg-white text-slate-700 hover:bg-emerald-50',
    topBarClass: 'bg-emerald-500',
    buttonClass: 'bg-emerald-500 hover:bg-emerald-600 text-white shadow-emerald-300',
  },
  {
    id: 'orange',
    title: 'Modellazione 3D',
    shortTitle: 'Modellazione 3D',
    icon: 'Box',
    colorHex: '#ff914d',
    badgeClass: 'bg-orange-100 text-orange-700 border-orange-300',
    cardBorderClass: 'border-orange-500 hover:border-orange-600',
    activeBgClass: 'bg-orange-500 text-white shadow-orange-200',
    inactiveBgClass: 'bg-white text-slate-700 hover:bg-orange-50',
    topBarClass: 'bg-orange-500',
    buttonClass: 'bg-orange-500 hover:bg-orange-600 text-white shadow-orange-300',
  },
  {
    id: 'yellow',
    title: 'Cittadinanza Digitale',
    shortTitle: 'Cittadinanza',
    icon: 'Globe',
    colorHex: '#eab308',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-300',
    cardBorderClass: 'border-amber-400 hover:border-amber-500',
    activeBgClass: 'bg-amber-400 text-slate-900 shadow-amber-200',
    inactiveBgClass: 'bg-white text-slate-700 hover:bg-amber-50',
    topBarClass: 'bg-amber-400',
    buttonClass: 'bg-amber-400 hover:bg-amber-500 text-slate-900 font-bold shadow-amber-200',
  },
];

export const CATEGORY_MAP = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c])
);

